### ISSUE TITLE
Cannot use ErrorModel in `Annotated` with an after-validator as expected

### ISSUE THREAD

**Issue by lmmx** [lmmx/validate-call-safe#2]
I expected to be able to augment the error model type with `Annotated`, but am getting an error that the modified error model type "is not callable".

```py
(validate-call-safe) louis 🚶 ~/lab/safe_calls $ qp -i demo.py 
Traceback (most recent call last):
  File "/home/louis/lab/safe_calls/demo.py", line 55, in <module>
    result = main()
  File "/home/louis/lab/safe_calls/demo.py", line 47, in main
    result = service(event=event)
TypeError: 'ErrorModel' object is not callable
```

I am unable to inspect why this error occurs (I tried both PDB and pysnooper), but I suspect this is coming from the type validation of the `error_model`, which is perhaps leading to the decorator using a different `@overload` signature? (in which case it would be clarified by using a kwarg instead of an arg: **which it is**).

This is preventing automated handling of the error model via after-validator (which would be desirable for arbitrary modification e.g. with Pydantic `Json`).

This seems to imply that

```py
T = TypeVar("T", bound=BaseModel)
```

is not being matched by the `validate_call` decorator, in this line:

```py
def validate_call_safe(
    error_model_or_func: type[T] | Callable[..., R] = ErrorModel,
```

My understanding is that `Annotated` would be ignored by such a type validation mechanism so this is surprising

Breakpointing within the module may help see what's going on

**Edit**: confirmed, it's the overly strict matching I'm doing preventing use of the `Annotated` generic as a model type at all, leading to its use as the decorated function [i.e. the wrong path is taken]

```py
> /home/louis/lab/validate-call-safe/src/validate_call_safe/decorator.py(85)validate_call_safe()
-> provided_err_model = pos_arg_is_cls and issubclass(error_model_or_func, BaseModel)
(Pdb) p pos_arg_is_cls
False
(Pdb) p error_model_or_func
typing.Annotated[validate_call_safe.errors.model.ErrorModel, AfterValidator(func=<class 'str'>)]
```

This check should unwrap annotated specifically then...

https://github.com/lmmx/validate-call-safe/blob/8f6d1dae3c37113de526b89fa623d1fbe7b8f995/src/validate_call_safe/decorator.py#L83

**Comment by lmmx** [comment]
Fixed by 3349da3, released in 0.3.3
