### ISSUE TITLE
Decorator option to wrap the `ReturnType` with result/success keys?

### ISSUE THREAD

**Issue by lmmx** [lmmx/validate-call-safe#4]
**Note**: this is inspired by the approach of [minder](https://github.com/lmmx/minder)

I'm not sure I'm keen on introducing generics here **but** it seems like a desirable pattern could be to take a function

```py
def f(a: str) -> int:
    return int(a)
```

and use a decorator argument [defaulting to False] such as

```py
@validate_call(extrude_result=True)
def g(a: str) -> int:
    return int(a)
```

to (implicitly) mutate its return signature from

```py
f: Callable[ParamSpec, ReturnType]
```

to

```py
g: Callable[ParamSpec, Success[ReturnType] | Failure[ErrorModel]
```

such that

```py
>>> f(a="1")
1
>>> f(a="b")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "<stdin>", line 1, in f
ValueError: invalid literal for int() with base 10: 'b'
```

would instead be

```py
>>> f(a="1")
{"success": True, "result": 1}
>>> f(a="b")
{"success": False, "result": ErrorModel(error_type="ValueError", ...)}
```

You would type this as something like

```py
ReturnType = TypeVar("ReturnType")

class SuccessTD[ReturnType](TypedDict):
    success: Literal[True]
    result: ReturnType

class FailureTD[ErrorModel](TypedDict):
    success: Literal[False]
    result: ErrorModel
```

```py
g: Callable[ParamSpec, SuccessTD[ReturnType] | FailureTD[ErrorModel])
```

or of course another model type (in fact, it can be both a TypedDict and a model)

```py
class SuccessModel(RootModel):
    root: SuccessTD[ReturnType]

class FailureModel(RootModel):
    root: FailureTD[ErrorModel]
```

or 'longform' as regular models, sans `TypedDict`

```py
class SuccessTD[ReturnType](BaseModel):
    success: Literal[True]
    result: ReturnType

class FailureTD[ErrorModel](BaseModel):
    success: Literal[False]
    result: ErrorModel

class FailureModel(BaseModel):
    root: FailureTD[ErrorModel]
```

- This implies mutating the return type, so perhaps it's undesirable?
- It'd be purely for when the return type was unstructured (e.g. just an `int` as in the example) and you'd want some way to detect it safely (as per the whole point of this), i.e. given `value = f()`, accessing result as `result.success` as cheaper [to type at least] than `isinstance` or

```py
match value:
    case ErrorModel():
        # Handle error
    case _:
        # Handle result
```

## A simpler way

The dead simple way to do this would be to just return dicts in the decorator's happy path and to add a model validator to the error model which extrudes the error model under a result key.

I'd actually need to see a use case before I took a position on this one

**Comment by lmmx** [comment]
I think ROP is an intriguing idea but this would make it more complex and go against the spirit of the original (not to mutate the return type on the happy path)
